// Generated by FMAutoIncBuild
// _1.0.0.352_
#define MAJORVER        1
#define MINORVER        0
#define BUILDVER        0
#define REVISIONVER     352
#define FILEPRODUCTVER        1,0,0,352
#define STRFILEPRODUCTVER     "1.00.0.352\0"
